config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here
    namespace :admin do
      resources :banners do
        collection do
          post :update_positions
        end
      end

      resources :banner_locations
    end
end

app/models/spree/banner.rb
class Spree::Banner < ActiveRecord::Base
  has_and_belongs_to_many :banner_locations,
                          class_name: 'Spree::BannerLocation',
                          join_table: 'spree_banner_banner_locations'

  belongs_to :product, touch: true, optional: true

  has_one_attached :image

  validates :link_url, presence: true, url: true, unless: -> { product }
  validates :name, :image, presence: true, unless: -> { product }
  validates :image, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  scope :published, -> { where(published: true).order('position ASC') }
  scope :location, ->(location) { joins(:banner_locations).where('spree_banner_locations.name = ?', location) }
  scope :product_banners, -> { published.where.not(product_id: nil).order('position ASC') }
  scope :image_banners, -> { published.where(product_id: nil).order('position ASC') }

  STYLES = {
    preview: [120, 120],
    thumbnail: [240, 240]
  }.freeze

  def initialize(attrs = nil)
    attrs ||= { published: true }
    super
  end

  def banner_name
    name.blank? && product.present? ? product.name : name
  end

  def banner_link
    link_url.blank? && product.present? ? product : link_url
  end

  def banner_image
    !image.attached? && product.present? && product.images.any? ? product.images.first.attachment : image.attachment
  end

  # Helper for resizing
  def preview
    image_form(:preview)
  end

  def thumbnail
    image_form(:thumbnail)
  end

  private

  def image_form(form)
    banner_image.variant(resize_to_limit: STYLES[form])
  end
end

app/models/spree/banner_location.rb
class Spree::BannerLocation < ActiveRecord::Base
  has_and_belongs_to_many :banners,
                          class_name: 'Spree::Banner',
                          join_table: 'spree_banner_banner_locations'

  validates :name, presence: true
end

app/models/spree/product_decorator.rb
module Spree
  module ProductDecorator

    def self.prepended(base)
      base.has_one :banner
      base.after_destroy :destroy_banner_if_deleted
    end

    def destroy_banner_if_deleted
      banner.update(published: false) if banner && deleted_at
    end

  end
end

::Spree::Product.prepend(Spree::ProductDecorator)

app/controllers/spree/admin/banner_locations_controller.rb
module Spree
  module Admin
    class BannerLocationsController < ResourceController
      respond_to :html

      def index
        @banner_locations = Spree::BannerLocation.order(:name)
      end
    end
  end
end

app/controllers/spree/admin/banners_controller.rb
module Spree
  module Admin
    class BannersController < ResourceController
      respond_to :html

      def index
        @banners = Spree::Banner.order(:position)
      end

      private

      def location_after_save
        if @banner.created_at == @banner.updated_at
          edit_admin_banner_url(@banner)
        else
          admin_banners_url
        end
      end

      def banner_params
        params.require(:banner).permit(:name, :body, :link_url, :published, :image, :position, :product_id)
      end
    end
  end
end

app/helpers/spree/admin/banners_helper.rb
module Spree
  module Admin
    module BannersHelper
      def get_column_header_by_type(type)
        return Spree.t(:name) if type == :image
        return Spree.t(:product) if type == :product

        return '----'
      end

      def get_image_link_by_type(banner, type)
        return link_to(banner.name, object_url(banner)) if type == :image
        return link_to(banner.product.name, object_url(banner)) if type == :product && banner.product

        return '----'
      end
    end
  end
end

app/views/spree/admin/banner_locations/_form.html.erb
<div class="row">

  <div class="col-md-12">
    <%= f.field_container :name do %>
      <%= f.label :name, t(:name) %><br>
      <%= f.text_field :name, class: "form-control fullwidth" %>
    <% end %>
  </div>

</div>

app/views/spree/admin/banner_locations/edit.html.erb
<% content_for :page_title do %>
  <%= t('spree_banner_locations.editing_location') %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to t('spree_banner_locations.back_to_locations'), spree.admin_banner_locations_path, icon: 'arrow-left' %>
<% end %>
<%= render 'spree/shared/error_messages', target: @banner_location %>
<%= form_for [:admin, @banner_location] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div data-hook="admin_banner_locations_method_edit_form_buttons">
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/banner_locations/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to t('spree_banner_locations.new_location'), new_object_url, { class: 'btn-success', icon: 'add', id: 'admin_new_banner_link' } %>
<% end %>
<% content_for :page_title do %>
  <%= t('spree_banner_locations.title') %>
<% end %>

<table class="table" id="listing_banner_locations" data-hook >
  <thead>
    <tr data-hook="admin_banners_index_headers">
      <th><%= Spree.t(:name) %></th>
      <th data-hook="admin_banners_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
  <% @banner_locations.each do |location|%>
    <tr>
      <td class="align-center"><%= location.name %></td>
      <td data-hook="admin_banner_locations_index_row_actions" class="actions">
        <%= link_to_edit location, no_text: true, class: 'edit' %>
        &nbsp;
        <%= link_to_delete location, no_text: true %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/banner_locations/new.html.erb
<% content_for :page_title do %>
  <%= t('spree_banner_locations.new_location') %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to t('spree_banner_locations.back_to_locations'), spree.admin_banner_locations_path, icon: 'arrow-left' %>
<% end %>
<%= render 'spree/shared/error_messages', :target => @banner_location %>
<%= form_for [:admin, @banner_location] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="clear"></div>

    <div data-hook="admin_shipping_method_new_form_buttons">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/banners/_edit_banner_locations.html.erb
<table class="table">
  <thead>
    <tr data-hook="banner_locations_header">
      <th><%= t('spree_banner_locations.title') %></th>
    </tr>
  </thead>
  <tbody id='banner_locations'>
    <tr data-hook="banner_locations_row">
      <td>
        <%= f.field_container :banner_location, class: ['form-group'] do %>
          <%= f.label :banner_location_id, Spree.t(:location) %>
          <%= f.collection_select(:banner_location_ids, Spree::BannerLocation.all, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', disabled: (cannot? :edit, Spree::BannerLocation) }) %>
          <%= f.error_message_on :banner_location %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<%= button_link_to t('spree_banner_locations.new_location'), 'javascript:;', {
      icon: 'add',
      'data-target': 'tbody#banner_locations',
      class: 'btn-success spree_add_fields'
} %>
<br/>
<br/>

app/views/spree/admin/banners/_form.html.erb
<div class="row">
  <div class="col-md-2">
    <%= f.field_container :position do %>
      <%= f.label :position, t(:position) %>
      <%= f.number_field :position, class: 'fullwidth form-control' %>
    <% end %>
  </div>

  <div class="col-md-10">
    <div class="field checkbox">
      <label>
        <%= f.check_box :published, class: "form-control" %>
        <%= t(:published) %>
      </label>
    </div>
  </div>

  <div class="col-md-12">
    <%= f.field_container :product_id do %>
      <%= label_tag :product_id, t(:product) %><br>
      <%= hidden_field_tag 'slide[product_id]', f.object.product_id.to_s, class: "product_picker fullwidth" %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :name do %>
      <%= f.label :name, t(:name) %><br>
      <%= f.text_field :name, class: 'fullwidth form-control', placeholder: t('spree_slider.placeholder_name') %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :link_url do %>
      <%= f.label :link_url, t(:link_url) %><br>
      <%= f.text_field :link_url, class: 'fullwidth form-control', placeholder: t('spree_slider.placeholder_link_url') %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= render 'spree/admin/banners/edit_banner_locations', f: f %>
  </div>

  <div class="col-md-12">
    <%= f.field_container :body do %>
      <%= f.label :body, t(:body) %><br>
      <%= f.text_area :body, {cols: 60, rows: 4, class: 'fullwidth form-control'} %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :image do %>
      <%= f.label :image, t(:image) %> <i>(<%= t('spree_slider.image_tip') %>)</i><br>
      <%= f.file_field :image %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :image do %>
      <% if f.object.image.attached? %>
        <p>
          <%= label_tag t(:preview) %>
          <br>
          <%= image_tag main_app.url_for(f.object.thumbnail), class: 'img-responsive' %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spree/admin/banners/edit.html.erb
<% content_for :page_title do %>
  <%= t('spree_banner.editing_banner') %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to t('spree_banner.back_to_banners'), spree.admin_banners_path, icon: 'arrow-left' %>
<% end %>
<%= render 'spree/shared/error_messages', target: @banner %>
<%= form_for [:admin, @banner], html: { multipart: true } do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div data-hook="admin_banners_edit_form_buttons">
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/banners/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to t('spree_banner.new_banner'), new_object_url, { class: 'btn-success', icon: 'add', id: 'admin_new_banner_link' } %>
<% end %>
<% content_for :page_title do %>
  <%= t('spree_banner.title') %>
<% end %>
<% product_banners = @banners.where.not(product_id: nil) %>
<% image_banners = @banners.where(product_id: nil) %>
<% [
  ['Image banners', image_banners, :image],
  ['Product banners', product_banners, :product]
  ].each do |translation, banners, type|%>
  <h3><%= translation %></h3>
  <table class="table sortable" id="listing_banners" data-hook data-sortable-link="<%= update_positions_admin_banners_url %>">
    <thead>
      <tr data-hook="admin_banners_index_headers">
        <th><%= Spree.t(:image) %></th>
        <th><%= get_column_header_by_type(type) %></th>
        <th><%= Spree.t(:published) %></th>
        <th data-hook="admin_banners_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% banners.each do |banner| %>
        <tr id="<%= spree_dom_id banner %>" data-hook="admin_banners_index_rows">
          <td><%= image_tag banner.banner_image ? main_app.url_for(banner.preview) : "noimage/small.png" %></td>
          <td><%= get_image_link_by_type(banner, type) %></td>
          <td><%= banner.published ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td data-hook="admin_banners_index_row_actions" class="actions text-right">
            <%= link_to_edit banner, no_text: true, class: 'edit' %>
            &nbsp;
            <%= link_to_delete banner, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
<% end %>

app/views/spree/admin/banners/new.html.erb
<% content_for :page_title do %>
  <%= t('spree_banner.new_banner') %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to t('spree_banner.back_to_banners'), spree.admin_banners_path, icon: 'arrow-left' %>
<% end %>
<%= render 'spree/shared/error_messages', target: @banner %>
<%= form_for [:admin, @banner] , html: { multipart: true } do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="clear"></div>

    <div data-hook="admin_shipping_method_new_form_buttons">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/banners/show.html.erb
<h1><%= t(:banner) %></h1>

<table class="table">
  <tr data-hook="product_id">
    <th><%= t(:product) %></th>
    <td>
      <%= @banner.product.name unless @banner.product_id.blank? %>
    </td>
  </tr>
  <tr data-hook="name">
    <th><%= t(:name) %></th>
    <td>
      <%= @banner.name %>
    </td>
  </tr>
  <tr data-hook="body">
    <th><%= t(:body) %></th>
    <td>
      <%= @banner.body %>
    </td>
  </tr>
  <tr data-hook="link_url">
    <th><%= t(:link_url) %></th>
    <td>
      <%= @banner.link_url %>
    </td>
  </tr>
  <tr data-hook="published">
    <th><%= t(:published) %></th>
    <td>
      <%= @banner.published ? t(:y) : t(:n) %>
    </td>
  </tr>
  <tr data-hook="image_file_name">
    <th><%= t(:image_file_name) %></th>
    <td>
      <%= @banner.image_file_name %>
    </td>
  </tr>
  <tr data-hook="position">
    <th><%= t(:position) %></th>
    <td>
      <%= @banner.position %>
    </td>
  </tr>
</table>

<p>
  <%= link_to_edit @banner, class: 'edit_banner' %> <%= t(:or) %>
  <%= link_to t(:back), collection_url %>
</p>